name: mozilla/ssh_scan
description: A SSH configuration and policy scanner
meta_description: Website and Blog for mozilla/ssh_scan

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://mozilla.github.io/ssh_scan/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://mozilla.github.io/ssh_scan/'
author:         'ssh_scan'
